// AUTO-GENERATED by scripts/parse-contenidos.mjs — do NOT edit by hand.
// Verbatim official Contenidos + Tercer-grado (3°) PDAs, NEM Fase 2 (Programa Sintético).
// Source: context/Programa_sintetico_fase_2.md

export type ContenidoPDA = { campo: string; contenido: string; pdas3: string[] }

export const CONTENIDOS_FASE2_3: ContenidoPDA[] = [
  {
    campo: 'Lenguajes',
    contenido:
      'Comunicación oral de necesidades, emociones, gustos, ideas y saberes, a través de los diversos lenguajes, desde una perspectiva comunitaria.',
    pdas3: [
      'De manera oral, expresa ideas completas sobre necesidades, vivencias, emociones, gustos, preferencias y saberes a distintas personas, combinando los lenguajes.',
      'Comprende, al interactuar con las demás personas, que existen diversas formas de comunicarse.',
      'Conversa y opina sobre diferentes temas y con varias personas interlocutoras.',
    ],
  },
  {
    campo: 'Lenguajes',
    contenido:
      'Narración de historias mediante diversos lenguajes, en un ambiente donde niñas y niños participen y se apropien de la cultura, a través de diferentes textos.',
    pdas3: [
      'Narra historias que inventa considerando los momentos de inicio, desarrollo y final, de manera individual o colectiva.',
      'Describe detalles de personajes y lugares, los comparte con sus pares para evocarlos y enriquecerlos, e incorpora nuevos elementos a partir de los rasgos de su cultura y de otras regiones.',
    ],
  },
  {
    campo: 'Lenguajes',
    contenido:
      'Recursos y juegos del lenguaje que fortalecen la diversidad de formas de expresión oral, y que rescatan la o las lenguas de la comunidad y de otros lugares.',
    pdas3: [
      'Propone y organiza con ayuda, juegos del lenguaje para invitar a sus pares a participar.',
      'Experimenta con los recursos de los lenguajes para crear, en lo individual y lo colectivo, juegos del lenguaje como adivinanzas, trabalenguas, canciones, rimas, coplas u otros.',
      'Combina e inventa nuevas palabras y las integra a su expresión.',
    ],
  },
  {
    campo: 'Lenguajes',
    contenido:
      'Reconocimiento y aprecio de la diversidad lingüística, al identificar las formas en que se comunican las distintas personas de la comunidad.',
    pdas3: [
      'Identifica y utiliza algunas palabras, frases o señas de la diversidad lingüística.',
      'Reconoce que algunos objetos se nombran de distinta manera, en diferentes regiones.',
      'Identifica que algunos nombres propios son de origen indígena y extranjero.',
      'Indaga, en distintas fuentes, el significado de términos o palabras que se utilizan en diferentes contextos o regiones.',
    ],
  },
  {
    campo: 'Lenguajes',
    contenido:
      'Representación gráfica de ideas y descubrimientos, al explorar los diversos textos que hay en su comunidad y otros lugares.',
    pdas3: [
      'Utiliza distintos textos (carteles, avisos, periódico mural, revistas, hojas, cuadernos) para representar gráficamente ideas que descubre del entorno de manera vivencial y al consultar libros, revistas y otras fuentes impresas y digitales.',
      'Expresa sus preferencias hacia ciertos textos e identifica algunas de sus funciones, como obtener información y disfrutar historias, entre otras.',
      'Interpreta y elabora algunas señalizaciones, símbolos y letreros a partir de entender sus características, elementos gráficos y contexto.',
    ],
  },
  {
    campo: 'Lenguajes',
    contenido:
      'Expresión de emociones y experiencias, en igualdad de oportunidades, apoyándose de recursos gráficos personales y de los lenguajes artísticos.',
    pdas3: [
      'Combina recursos gráficos y de los lenguajes artísticos, en la representación de emociones y experiencias.',
      'Explica y comparte sus producciones con las y los demás, dice o señala qué quiso representar y describe detalles para enfatizar ciertas emociones o experiencias.',
      'Argumenta su opinión acerca de las producciones de sus pares.',
      'Compara sus producciones con las de sus pares, para encontrar semejanzas en los elementos artísticos utilizados y en algunas emociones y experiencias.',
      'Reconoce que las demás personas tienen el mismo derecho para expresarse.',
    ],
  },
  {
    campo: 'Lenguajes',
    contenido:
      'Producciones gráficas dirigidas a diversas destinatarias y diversos destinatarios, para establecer vínculos sociales y acercarse a la cultura escrita.',
    pdas3: [
      'Planifica producciones gráficas, tales como avisos, recomendaciones de libros, recados, letreros, entre otros, de forma individual o en pequeños equipos.',
      'Recurre a diversos textos para copiar palabras, combinar letras del nombre propio, el de sus pares o dicta a alguna persona adulta, para establecer vínculos con las familias, la escuela y la comunidad.',
      'Usa grafías para representar su nombre y otras palabras conocidas con diversos propósitos.',
      'Reconoce las letras de su nombre en textos impresos y digitales.',
    ],
  },
  {
    campo: 'Lenguajes',
    contenido:
      'Reconocimiento de ideas o emociones en la interacción con manifestaciones culturales y artísticas y con la naturaleza, a través de diversos lenguajes.',
    pdas3: [
      'Explica lo que le gusta o disgusta, lo que se imagina y le provocan las manifestaciones culturales y artísticas (pinturas, zonas arqueológicas, poemas, artesanías, entre otras), a partir de sus elementos, como formas, trazos, personas, objetos o sonidos y ritmos.',
      'Aprecia y expresa gusto por ciertas manifestaciones o por alguna o algún artista.',
      'Relaciona en algunas manifestaciones artísticas y culturales, sucesos personales o familiares, así como lo que pasa en su comunidad.',
      'Escucha lo que le comparten sus pares y reconoce que hay diversidad de opiniones, gustos o disgustos alrededor de una misma manifestación artística o cultural.',
    ],
  },
  {
    campo: 'Lenguajes',
    contenido:
      'Producción de expresiones creativas con los distintos elementos de los lenguajes artísticos.',
    pdas3: [
      'Enriquece sus producciones creativas de expresión gráfica o corporal, al incluir o retomar elementos, tales como líneas, combinación de colores, formas, imágenes, gestos, posturas, sonidos, entre otros, de las manifestaciones artísticas y culturales.',
      'Aprecia y opina sobre las creaciones de sus pares y otros artistas de la comunidad.',
    ],
  },
  {
    campo: 'Saberes y Pensamiento Científico',
    contenido:
      'Exploración de la diversidad natural que existe en la comunidad y en otros lugares.',
    pdas3: [
      'Distingue algunas características del entorno natural: plantas, animales, cuerpos de agua, clima, entre otras.',
      'Se apoya en recursos impresos y digitales como fotografías, imágenes o videos para profundizar en sus conocimientos acerca de la diversidad de la naturaleza en su comunidad y otras regiones.',
      'Establece con sus pares, formas de organizar a los seres vivos y elementos de la naturaleza para establecer semejanzas y diferencias a la vez que aprecia su diversidad.',
      'Observa y experimenta con elementos de la naturaleza, comunica y registra sus hallazgos.',
      'Explica con sus palabras y en su lengua materna, procesos, fenómenos naturales y experimentos; los representa con recursos gráficos.',
    ],
  },
  {
    campo: 'Saberes y Pensamiento Científico',
    contenido:
      'Saberes familiares y comunitarios que resuelven situaciones y necesidades en el hogar y la comunidad.',
    pdas3: [
      'Propone algunos saberes familiares y comunitarios, para resolver necesidades y situaciones en su hogar, escuela y comunidad.',
      'Distingue, con ayuda de otras personas, situaciones en las que los saberes comunitarios son útiles y cuándo deben complementarse y/o contrastarse con otros conocimientos; cuidando su integridad y la de los demás.',
      'Indaga en distintas fuentes de consulta, incluyendo medios impresos y digitales, saberes y prácticas de otros lugares para cuidar la naturaleza.',
    ],
  },
  {
    campo: 'Saberes y Pensamiento Científico',
    contenido:
      'Los seres vivos: elementos, procesos y fenómenos naturales que ofrecen oportunidades para entender y explicar hechos cotidianos, desde distintas perspectivas.',
    pdas3: [
      'Planifica de manera colaborativa indagaciones para ampliar sus conocimientos sobre la naturaleza, el planeta y el universo: hace preguntas, explora su entorno, expone sus ideas, busca información, compara lo que sabe, registra datos y explica sus hallazgos.',
      'Explica con sus palabras y en su lengua materna, la importancia del aire, el agua, el suelo y el sol para todos los seres vivos.',
      'Expresa lo que supone sucedería si se alteran las condiciones de la naturaleza por las acciones de las personas, por ejemplo, al contaminarla o dañarla.',
      'Explica con sus palabras cómo suceden y por qué se producen los fenómenos naturales de su entorno o de otros lugares: la actividad de un volcán, la nieve, una cascada, el granizo, un eclipse, entre otros. Se apoya de diversos recursos para ampliar lo que sabe.',
      'Indaga acerca de cómo funciona su cuerpo, sus cambios físicos, y explica lo que entiende.',
    ],
  },
  {
    campo: 'Saberes y Pensamiento Científico',
    contenido:
      'Los saberes numéricos como herramienta para resolver situaciones del entorno, en diversos contextos socioculturales.',
    pdas3: [
      'Dice la serie numérica en orden y amplía su rango de conteo.',
      'Cuenta objetos y elementos de su entorno en su lengua materna con diversos propósitos.',
      'Construye colecciones y las compara mediante distintas estrategias para determinar cuál tiene más o menos elementos.',
      'Representa cantidades, con dibujos, símbolos personales y numerales e interpreta los registros de sus pares.',
      'Construye y compara colecciones, usando distintas estrategias.',
      'Ordena elementos de una serie y usa números ordinales para expresar el lugar que ocupa cada elemento.',
      'Organiza y registra información en tablas o cuadros sencillos.',
      'Propone, de manera colaborativa, formas de resolver situaciones cotidianas e imaginarias que involucran acciones de agregar, juntar, quitar, separar, comparar e igualar cantidades.',
      'Reconoce el valor de monedas y billetes al usarlos en situaciones reales y de juego y estima para qué le alcanza.',
      'Intercambia con sus pares, saberes numéricos para plantear problemas y encontrar distintas estrategias para resolverlos de formas diversas y equitativas.',
      'Conoce formas de contar en otras culturas, como la maya, que usa rayas y puntos para representar los números.',
    ],
  },
  {
    campo: 'Saberes y Pensamiento Científico',
    contenido:
      'El dominio del espacio y reconocimiento de formas en el entorno desde diversos puntos de observación y mediante desplazamientos o recorridos.',
    pdas3: [
      'Expresa la posición y ubicación de objetos, lugares y personas con respecto a su cuerpo y a otros objetos; usa gradualmente referentes convencionales.',
      'Interpreta y comunica en su lengua materna, recorridos y trayectorias con referentes espaciales de orientación y proximidad (cerca, lejos, arriba, abajo, delante, detrás, derecha, izquierda).',
      'Planifica y dibuja recorridos, de su comunidad y de otros espacios, que contribuyen a reconocer el lugar donde vive.',
      'Observa y reconoce atributos geométricos en objetos y elementos de su entorno, y los describe con sus palabras y con términos convencionales.',
      'Representa y reproduce objetos, animales y plantas con el tangram, bloques de construcción, modelado, doblado de papel o con dibujos.',
      'Crea patrones de repetición y crecimiento para hacer secuencias.',
      'Imagina y anticipa los cambios que ocurrirán al manipular, apilar, rasgar y transformar objetos, haciendo composiciones geométricas.',
    ],
  },
  {
    campo: 'Saberes y Pensamiento Científico',
    contenido:
      'Las magnitudes de longitud, peso, capacidad y tiempo en situaciones cotidianas del hogar y del entorno sociocultural.',
    pdas3: [
      'Estima y compara la longitud de dos o más objetos con apoyo de un intermediario, y expresa cuál es más largo, más corto, más ancho, más angosto o si son iguales; contrasta sus ideas con las de sus pares y las representa de manera gráfica.',
      'Mide objetos, áreas o distancias con unidades no convencionales que tiene al alcance y explica por qué son apropiadas; las representa de manera gráfica.',
      'Usa balanzas o básculas para comparar el peso de dos o más objetos.',
      'Trasvasa arena o líquidos entre recipientes de distintos tamaños y formas para medir su capacidad, y dice en cuál cabe más o menos.',
      'Percibe el paso del tiempo mediante eventos y procesos, con apoyo de la observación de cambios en la naturaleza, como el día y la noche, las estaciones del año, las temporadas de cosecha, el crecimiento de seres vivos o cualquier evento importante de la comunidad.',
      'Hace uso de instrumentos que miden el paso del tiempo, tales como calendarios, relojes de arena, solares, digitales y análogos.',
    ],
  },
  {
    campo: 'Saberes y Pensamiento Científico',
    contenido:
      'Clasificación y experimentación con objetos y elementos del entorno que reflejan la diversidad de la comunidad o región.',
    pdas3: [
      'Recolecta objetos y elementos de su entorno para observarlos, hacer preguntas y explorar sus características y comportamiento.',
      'Dialoga con sus pares para definir criterios de clasificación de objetos y elementos del entorno natural y sociocultural, que respondan a distintos propósitos.',
      'Elabora e interpreta registros para organizar objetos y elementos del entorno mediante dibujos, tablas, símbolos o pictogramas; los explica a otras personas, en su lengua materna y con sus palabras.',
      'Experimenta, de manera colaborativa, con elementos y objetos del entorno y reconoce si hay cambios o transformaciones en ellos, manteniendo normas de seguridad.',
      'Usa herramientas diversas en situaciones experimentales: lupas, microscopios, goteros, vasos medidores, balanzas, termómetro, lámparas, cernidores, entre otros.',
    ],
  },
  {
    campo: 'Saberes y Pensamiento Científico',
    contenido:
      'Características de objetos y comportamiento de los materiales del entorno sociocultural.',
    pdas3: [
      'Describe las características de los objetos y materiales de su entorno.',
      'Experimenta con distintos objetos para reconocer sus características y propiedades al manipularlos, combinarlos o transformarlos.',
      'Explica los resultados de sus experimentos y los contrasta con los hallazgos de sus pares, confirma o modifica sus suposiciones iniciales.',
      'Reconoce que las comunidades usan de diferente manera los objetos y materiales propios de su cultura: elaboran artesanías con papel, barro o arcilla, elaboran textiles, ropa y hacen bordados con diferentes materiales.',
      'Distingue los materiales de la naturaleza, de los fabricados por el ser humano.',
      'Experimenta con diversos objetos o instrumentos musicales, para producir y combinar diferentes sonidos.',
    ],
  },
  {
    campo: 'Saberes y Pensamiento Científico',
    contenido:
      'Objetos y artefactos tecnológicos que mejoran y facilitan la vida familiar y de la comunidad.',
    pdas3: [
      'Indaga acerca del funcionamiento de juguetes, objetos y artefactos tecnológicos de distintos contextos y reconoce su beneficio.',
      'Imagina y propone con sus pares, nuevas formas de usar los objetos y artefactos tecnológicos para aprovecharlos de manera sustentable: usar una cuchara para comer, medir ingredientes o remover tierra para sembrar.',
      'Reconoce que las personas utilizan diferentes objetos o artefactos tecnológicos para desarrollar su oficio o profesión, en beneficio propio y de la comunidad.',
    ],
  },
  {
    campo: 'Ética, Naturaleza y Sociedades',
    contenido:
      'Interacción, cuidado, conservación y regeneración de la naturaleza, que favorece la construcción de una conciencia socioambiental.',
    pdas3: [
      'Interactúa con respeto y empatía en la naturaleza, e identifica algunos elementos y cuidados que necesitan los seres vivos.',
      'Manifiesta interés por cuidar a la naturaleza y encuentra formas creativas de resolver problemas socioambientales de su comunidad, como la contaminación, la deforestación, el cambio climático, el deshielo o la sobreexplotación de los recursos naturales.',
      'Reconoce algunas condiciones ambientales de su comunidad y dice cómo afectan a plantas, animales y personas; en colaboración, hace propuestas para mejorarlas.',
    ],
  },
  {
    campo: 'Ética, Naturaleza y Sociedades',
    contenido:
      'Transformación responsable del entorno al satisfacer necesidades básicas de alimentación, vestido y vivienda.',
    pdas3: [
      'Asocia los recursos naturales de donde provienen algunos alimentos y explica con sus palabras, cómo cambia la naturaleza al obtenerlos y producirlos, así como al elaborar o fabricar prendas de vestir.',
      'Indaga los materiales con los que se construyen las viviendas y reconoce que se obtienen de la naturaleza.',
      'Cuida los bienes que provienen de la naturaleza al satisfacer necesidades y promueve que las demás personas también lo hagan.',
      'Sugiere y lleva a cabo algunas acciones sustentables a su alcance, para cuidar el ambiente natural y fomentar el buen vivir de las personas de la comunidad.',
    ],
  },
  {
    campo: 'Ética, Naturaleza y Sociedades',
    contenido:
      'Construcción de la identidad y pertenencia a una comunidad y país a partir del conocimiento de su historia, sus celebraciones, conmemoraciones tradicionales y obras del patrimonio artístico y cultural.',
    pdas3: [
      'Aprecia la riqueza de la historia de su comunidad a través de relatos, historias, leyendas, mitos, conmemoraciones, celebraciones tradicionales, obras culturales y artísticas.',
      'Se interesa, junto con sus pares, por conocer la diversidad cultural y artística de otras regiones del país, así como otras costumbres y tradiciones que enriquecen su visión del país y del mundo.',
      'Entiende que los símbolos patrios representan los valores y la historia de México y los explica con sus propias palabras; reconoce los lugares y momentos apropiados para usarlos.',
      'Reconoce que algunas tradiciones surgen de situaciones, eventos o vivencias comunitarias relevantes y que se modifican con el paso del tiempo.',
    ],
  },
  {
    campo: 'Ética, Naturaleza y Sociedades',
    contenido:
      'Cambios que ocurren en los lugares, entornos, objetos, costumbres y formas de vida de las distintas familias y comunidades con el paso del tiempo.',
    pdas3: [
      'Identifica, con ayuda, y a través de narraciones, cartas, fotografías, objetos, ropa y otros elementos, acontecimientos y sucesos importantes ocurridos en su familia a lo largo del tiempo.',
      'Comprende que, con el paso del tiempo, se modifican los paisajes, los objetos, las costumbres y las formas de vida de la comunidad, por lo que se debe actuar con responsabilidad para el bienestar individual y colectivo.',
    ],
  },
  {
    campo: 'Ética, Naturaleza y Sociedades',
    contenido:
      'Labores y servicios que contribuyen al bien común de las distintas familias y comunidades.',
    pdas3: [
      'Aprecia las labores y servicios que existen en la comunidad y valora el impacto que tienen para el bienestar común.',
      'Utiliza lo que sabe de los trabajos y servicios que existen en su comunidad, para proponer nuevas formas de colaborar y contribuir al bienestar de todas las personas.',
    ],
  },
  {
    campo: 'Ética, Naturaleza y Sociedades',
    contenido:
      'Los derechos de niñas y niños como base para el bienestar integral y el establecimiento de acuerdos que favorecen la convivencia pacífica.',
    pdas3: [
      'Explica con sus palabras y mediante otros lenguajes, lo que entiende de cada uno de los derechos de niñas y niños, y escucha las opiniones de sus pares.',
      'Difunde los derechos de las niñas y los niños en su escuela y entorno cercano, para favorecer que todas las personas los respeten y contribuyan a su ejercicio.',
      'Reconoce que una convivencia pacífica se basa en el respeto de los derechos de todas y todos.',
    ],
  },
  {
    campo: 'Ética, Naturaleza y Sociedades',
    contenido:
      'La diversidad de personas y familias en la comunidad y su convivencia, en un ambiente de equidad, libertad, inclusión y respeto a los derechos humanos.',
    pdas3: [
      'Reconoce las distintas formas de ser y actuar de sus pares, para convivir en armonía.',
      'Conversa con sus pares acerca de lo que significa pertenecer a una familia, los cuidados que reciben, las reglas que deben seguir, algunas de sus costumbres, y reconoce que se conforman de diferente manera, sin que una tenga más valor que otra.',
    ],
  },
  {
    campo: 'Ética, Naturaleza y Sociedades',
    contenido:
      'La cultura de paz como una forma de relacionarse con otras personas para promover la inclusión y el respeto a la diversidad.',
    pdas3: [
      'Se expresa y participa con libertad y respeto en diversas situaciones y contextos, favoreciendo una cultura de paz y la convivencia pacífica en un marco de inclusión y diversidad.',
      'Reconoce los desacuerdos como oportunidades para construir un ambiente de equidad e inclusión.',
    ],
  },
  {
    campo: 'De lo Humano y lo Comunitario',
    contenido:
      'Construcción de la identidad personal a partir de su pertenencia a un territorio, su origen étnico, cultural y lingüístico, y la interacción con personas cercanas.',
    pdas3: [
      'Identifica que la lengua que habla, las costumbres familiares y el lugar donde vive contribuyen a la formación de su identidad y pertenencia a una comunidad en la que participa y colabora.',
      'Aprecia las características y cualidades propias, así como las de sus pares y de otras personas.',
      'Muestra seguridad y confianza en sus formas de ser, actuar, pensar e interactuar en la casa, escuela y comunidad.',
      'Expresa y representa con recursos de los distintos lenguajes, la imagen que tiene de sí y de las y los demás.',
    ],
  },
  {
    campo: 'De lo Humano y lo Comunitario',
    contenido:
      'Posibilidades de movimiento en diferentes espacios, para favorecer las habilidades motrices.',
    pdas3: [
      'Combina movimientos que implican el control, equilibrio y estabilidad del cuerpo al realizar acciones individuales, en parejas o en colectivo.',
      'Incorpora en sus movimientos elementos de la estructura del espacio físico como la distancia, la dirección, la temporalidad, la velocidad, la posición y la lateralidad.',
      'Coordina movimientos con control y equilibrio al resolver situaciones cotidianas, participar en juegos tradicionales y representaciones individuales o colectivas en igualdad de oportunidades y sin distinción de género.',
      'Reconoce cuando realiza un sobreesfuerzo físico: dolor torácico, mareos, deshidratación o dificultad para respirar; pone en práctica estrategias que le ayudan a recuperar un estado de bienestar.',
    ],
  },
  {
    campo: 'De lo Humano y lo Comunitario',
    contenido:
      'Precisión y coordinación en los movimientos al usar objetos, herramientas y materiales, de acuerdo con sus condiciones, capacidades y características.',
    pdas3: [
      'Resuelve situaciones cotidianas mediante el uso de objetos, herramientas y materiales que implican el control y precisión de movimientos para satisfacer necesidades personales y colectivas.',
      'Construye y modela objetos, con control y precisión de sus movimientos; selecciona objetos, herramientas y materiales apropiados para resolver situaciones diversas.',
      'Respeta y pone en práctica, medidas de seguridad al manipular objetos, herramientas y materiales en diferentes lugares.',
    ],
  },
  {
    campo: 'De lo Humano y lo Comunitario',
    contenido: 'Las emociones en la interacción con diversas personas y situaciones.',
    pdas3: [
      'Establece vínculos afectivos y de empatía con sus pares y otras personas, a partir de la convivencia cotidiana.',
      'Intercambia experiencias y vivencias con sus pares y otras personas, acerca de las diferentes formas de actuar, expresar, nombrar y controlar las emociones.',
      'Dice lo que le molesta o incomoda para evitar reaccionar con gritos o agresión; dialoga y respeta las reglas para una mejor convivencia.',
      'Identifica situaciones en las que percibe que está en riesgo su integridad o la de otras personas.',
      'Conversa con sus pares acerca de lo que hacen para enfrentar situaciones de riesgo y buscan distintas alternativas para sentir seguridad y ponerse a salvo.',
    ],
  },
  {
    campo: 'De lo Humano y lo Comunitario',
    contenido:
      'Interacción con personas de diversos contextos, que contribuyan al establecimiento de relaciones positivas y a una convivencia basada en la aceptación de la diversidad.',
    pdas3: [
      'Propone y lleva a cabo formas de convivencia libres de violencia en la casa, escuela y comunidad.',
      'Se integra con seguridad y confianza en actividades colectivas al interactuar con personas de otros lugares y culturas.',
      'Asume actitudes prosociales como compartir, ayudar y colaborar, al participar y mejorar las relaciones de convivencia con las demás personas.',
    ],
  },
  {
    campo: 'De lo Humano y lo Comunitario',
    contenido:
      'Cuidado de la salud personal y colectiva, al llevar a cabo acciones de higiene, limpieza, y actividad física, desde los saberes prácticos de la comunidad y la información científica.',
    pdas3: [
      'Reconoce algunos factores que permiten conservar la salud y los que la perjudican.',
      'Propone acciones que contribuyen a mantener su salud y bienestar, relacionadas con higiene personal, limpieza y actividad física, considerando los saberes prácticos de la comunidad y las aportaciones científicas.',
      'Promueve acciones sobre el cuidado de la salud visual, auditiva, bucal, alimentaria y física, en la casa, escuela y comunidad.',
      'Dialoga con sus pares y toman acuerdos para el cuidado de la salud en beneficio de todas y todos.',
    ],
  },
  {
    campo: 'De lo Humano y lo Comunitario',
    contenido:
      'Consumo de alimentos y bebidas que benefician la salud, de acuerdo con los contextos socioculturales.',
    pdas3: [
      'Obtiene información de diversas fuentes, acerca de los factores que favorecen estilos de vida saludable, destacando el consumo de alimentos nutritivos y de agua simple potable, entre otros.',
      'Aprecia la cultura alimentaria mexicana, y descubre la diversidad de ingredientes que existen en el país, así como la influencia de otras culturas en el consumo y preparación de alimentos.',
      'Promueve el consumo de alimentos sanos propios de su comunidad y la creación de huertos para la siembra y cosecha de frutas y verduras.',
    ],
  },
  {
    campo: 'De lo Humano y lo Comunitario',
    contenido:
      'Medidas de prevención de accidentes y situaciones de riesgo de acuerdo con el contexto, para el cuidado de la integridad personal y colectiva.',
    pdas3: [
      'Indaga en diferentes fuentes de consulta y con expertos, acerca de los posibles riesgos y daños que provocan algunos fenómenos naturales como: sismos, inundaciones, huracanes, entre otros.',
      'Propone y lleva a cabo, acciones de seguridad y formas de colaboración en situaciones de riesgo, accidentes o desastres, tomando en cuenta el bienestar de las personas y otros seres vivos de la comunidad.',
      'Colabora en acciones de difusión, al promover una cultura de prevención de accidentes y riesgos para el beneficio común.',
    ],
  },
]
