// Word → emoji for game visuals (v1 of "real" images). Curated for common preschool English
// vocabulary; render-time fallback that works offline, retroactively, and for deterministic games.
// AI builders may also store a sense-correct `emoji` per item which takes precedence over this map.
// Later: swap/augment with Twemoji SVGs (cross-device consistency) or a real/gen-AI image source.
const EMOJI: Record<string, string> = {
  // Animals
  cat: '🐱',
  dog: '🐶',
  bird: '🐦',
  fish: '🐟',
  cow: '🐮',
  pig: '🐷',
  horse: '🐴',
  sheep: '🐑',
  duck: '🦆',
  chicken: '🐔',
  hen: '🐔',
  rabbit: '🐰',
  bunny: '🐰',
  mouse: '🐭',
  frog: '🐸',
  lion: '🦁',
  tiger: '🐯',
  bear: '🐻',
  monkey: '🐵',
  elephant: '🐘',
  giraffe: '🦒',
  zebra: '🦓',
  snake: '🐍',
  turtle: '🐢',
  bee: '🐝',
  butterfly: '🦋',
  spider: '🕷️',
  ant: '🐜',
  ladybug: '🐞',
  fox: '🦊',
  wolf: '🐺',
  owl: '🦉',
  penguin: '🐧',
  whale: '🐳',
  dolphin: '🐬',
  shark: '🦈',
  octopus: '🐙',
  crab: '🦀',
  snail: '🐌',
  dinosaur: '🦕',
  dragon: '🐲',
  unicorn: '🦄',
  deer: '🦌',
  goat: '🐐',
  kangaroo: '🦘',
  koala: '🐨',
  panda: '🐼',
  hippo: '🦛',
  rhino: '🦏',
  camel: '🐪',
  // Food & drink
  apple: '🍎',
  banana: '🍌',
  orange: '🍊',
  grape: '🍇',
  grapes: '🍇',
  strawberry: '🍓',
  watermelon: '🍉',
  lemon: '🍋',
  cherry: '🍒',
  peach: '🍑',
  pear: '🍐',
  pineapple: '🍍',
  bread: '🍞',
  cheese: '🧀',
  egg: '🥚',
  milk: '🥛',
  water: '💧',
  juice: '🧃',
  cake: '🍰',
  cookie: '🍪',
  candy: '🍬',
  icecream: '🍦',
  'ice cream': '🍦',
  pizza: '🍕',
  hamburger: '🍔',
  hotdog: '🌭',
  taco: '🌮',
  rice: '🍚',
  soup: '🍲',
  carrot: '🥕',
  corn: '🌽',
  tomato: '🍅',
  potato: '🥔',
  broccoli: '🥦',
  mushroom: '🍄',
  honey: '🍯',
  popcorn: '🍿',
  chocolate: '🍫',
  // Body
  eye: '👁️',
  eyes: '👀',
  ear: '👂',
  nose: '👃',
  mouth: '👄',
  tooth: '🦷',
  teeth: '🦷',
  hand: '✋',
  foot: '🦶',
  leg: '🦵',
  hair: '💇',
  face: '🙂',
  head: '😀',
  tongue: '👅',
  heart: '❤️',
  // Family & people
  baby: '👶',
  boy: '👦',
  girl: '👧',
  man: '👨',
  woman: '👩',
  mom: '👩',
  mother: '👩',
  dad: '👨',
  father: '👨',
  family: '👨‍👩‍👧‍👦',
  grandma: '👵',
  grandpa: '👴',
  teacher: '👩‍🏫',
  doctor: '👩‍⚕️',
  baby_girl: '👶',
  friend: '🧑‍🤝‍🧑',
  // Nature & weather
  sun: '☀️',
  moon: '🌙',
  star: '⭐',
  stars: '✨',
  cloud: '☁️',
  rain: '🌧️',
  snow: '❄️',
  snowman: '⛄',
  rainbow: '🌈',
  tree: '🌳',
  flower: '🌸',
  leaf: '🍃',
  grass: '🌿',
  plant: '🌱',
  fire: '🔥',
  mountain: '⛰️',
  sky: '🌌',
  wind: '🌬️',
  lightning: '⚡',
  earth: '🌍',
  rock: '🪨',
  // Transport
  car: '🚗',
  bus: '🚌',
  truck: '🚚',
  train: '🚂',
  plane: '✈️',
  airplane: '✈️',
  boat: '⛵',
  ship: '🚢',
  bike: '🚲',
  bicycle: '🚲',
  rocket: '🚀',
  helicopter: '🚁',
  taxi: '🚕',
  police: '🚓',
  ambulance: '🚑',
  firetruck: '🚒',
  tractor: '🚜',
  scooter: '🛴',
  // School & objects
  book: '📖',
  pencil: '✏️',
  pen: '🖊️',
  crayon: '🖍️',
  scissors: '✂️',
  paper: '📄',
  ruler: '📏',
  bag: '🎒',
  backpack: '🎒',
  glue: '🧴',
  paint: '🎨',
  brush: '🖌️',
  clock: '🕐',
  ball: '⚽',
  balloon: '🎈',
  kite: '🪁',
  toy: '🧸',
  teddy: '🧸',
  bell: '🔔',
  key: '🔑',
  phone: '📱',
  computer: '💻',
  camera: '📷',
  television: '📺',
  tv: '📺',
  lamp: '💡',
  umbrella: '☔',
  gift: '🎁',
  // Clothes
  shirt: '👕',
  tshirt: '👕',
  pants: '👖',
  dress: '👗',
  shoe: '👟',
  shoes: '👟',
  sock: '🧦',
  socks: '🧦',
  hat: '👒',
  cap: '🧢',
  coat: '🧥',
  glove: '🧤',
  gloves: '🧤',
  boot: '👢',
  boots: '👢',
  scarf: '🧣',
  glasses: '👓',
  // House
  house: '🏠',
  home: '🏠',
  door: '🚪',
  window: '🪟',
  bed: '🛏️',
  chair: '🪑',
  table: '🪑',
  cup: '☕',
  plate: '🍽️',
  spoon: '🥄',
  fork: '🍴',
  knife: '🔪',
  bath: '🛁',
  toilet: '🚽',
  soap: '🧼',
  towel: '🧻',
  broom: '🧹',
  clock_house: '🕰️',
  // Colors (swatches)
  red: '🔴',
  blue: '🔵',
  green: '🟢',
  yellow: '🟡',
  orange_color: '🟠',
  purple: '🟣',
  pink: '🩷',
  brown: '🟤',
  black: '⚫',
  white: '⚪',
  gray: '⬜',
  grey: '⬜',
  gold: '🟨',
  // Shapes & misc
  circle: '⭕',
  square: '🟦',
  triangle: '🔺',
  star_shape: '⭐',
  heart_shape: '❤️',
  // Numbers
  one: '1️⃣',
  two: '2️⃣',
  three: '3️⃣',
  four: '4️⃣',
  five: '5️⃣',
  six: '6️⃣',
  seven: '7️⃣',
  eight: '8️⃣',
  nine: '9️⃣',
  ten: '🔟',
  zero: '0️⃣',
  // Actions / verbs
  run: '🏃',
  jump: '🤸',
  walk: '🚶',
  sleep: '😴',
  eat: '🍽️',
  drink: '🥤',
  read: '📖',
  write: '✍️',
  sing: '🎤',
  dance: '💃',
  swim: '🏊',
  play: '🎮',
  cry: '😢',
  laugh: '😂',
  smile: '😊',
  happy: '😄',
  sad: '😢',
  angry: '😠',
  cook: '👩‍🍳',
  draw: '🎨',
  clap: '👏',
  wave: '👋',
  sit: '🪑',
  stand: '🧍',
  // Seeded-vocab additions (TG5A / common preschool)
  ape: '🦍',
  arrow: '🏹',
  astronaut: '👨‍🚀',
  box: '📦',
}

// True only when `s` is a real emoji glyph (contains a pictographic codepoint and NO ascii letters).
// Rejects the garbage the AI sometimes returns in an `emoji` field (a stray letter like "h"/"v"/"n",
// or plain text). Keycap digits (1️⃣) and bare symbols correctly fail and fall through to a real visual.
export function isEmoji(s: string | null | undefined): boolean {
  if (!s) return false
  const t = s.trim()
  if (!t || t.length > 12) return false
  if (/[a-zA-Z]/.test(t)) return false
  // No \p{} / u-flag (TS target) — detect via codepoints: astral surrogate (most emoji),
  // a variation selector (emoji presentation), or BMP symbol/arrow/dingbat ranges.
  for (let i = 0; i < t.length; i++) {
    const c = t.charCodeAt(i)
    if (c >= 0xd800 && c <= 0xdbff) return true
    if (c === 0xfe0f) return true
    if (c >= 0x2190 && c <= 0x2bff) return true
  }
  return false
}

// For builders: keep the model's `emoji` only if it's actually an emoji, else drop it.
export function sanitizeEmoji(s: string | null | undefined): string | undefined {
  return isEmoji(s) ? s!.trim() : undefined
}

// Normalize a word and look up its emoji. Handles articles, casing, and simple plurals.
export function wordToEmoji(word: string): string | null {
  if (!word) return null
  const w = word
    .toLowerCase()
    .trim()
    .replace(/^(a|an|the)\s+/, '')
    .replace(/[^a-z\s]/g, '')
    .trim()
  if (EMOJI[w]) return EMOJI[w]
  // simple plural → singular
  if (w.endsWith('ies') && EMOJI[w.slice(0, -3) + 'y']) return EMOJI[w.slice(0, -3) + 'y']
  if (w.endsWith('es') && EMOJI[w.slice(0, -2)]) return EMOJI[w.slice(0, -2)]
  if (w.endsWith('s') && EMOJI[w.slice(0, -1)]) return EMOJI[w.slice(0, -1)]
  // first token of a phrase
  const first = w.split(/\s+/)[0]
  if (first && EMOJI[first]) return EMOJI[first]
  return null
}
