-- AUTO-GENERATED by scripts/parse-richmond-units.mjs from richmond_units/*.md — do NOT edit by hand.
-- Real TG5A content: 8 units × 4 lesson groups. Idempotent upserts (safe to re-apply).

insert into richmond_units (book_code, unit_number, unit_title) values
  ('TG5A', 1, 'My Busy Week'),
  ('TG5A', 2, 'Look at My Family!'),
  ('TG5A', 3, 'Amazing Animals'),
  ('TG5A', 4, 'I''m Healthy and Safe'),
  ('TG5A', 5, 'My Community'),
  ('TG5A', 6, 'Saving the Planet'),
  ('TG5A', 7, 'Going Places'),
  ('TG5A', 8, 'Present, Past and Future')
on conflict (book_code, unit_number) do update set unit_title = excluded.unit_title;

-- Unit 1: My Busy Week
insert into richmond_lesson_groups (unit_id, lesson_range, lesson_start, lesson_end, learning_goals, vocabulary, language_models, sort_order)
select u.id, '1-4', 1, 4, ARRAY['To say one''s name and to greet others', 'To identify and say daily classroom routines', 'To say which school activities one can do', 'To say one''s gender and age', 'To describe school routines one likes or doesn''t like to do', 'To say what Dino''s favorite things are', 'To describe one''s favorite things']::text[], ARRAY['sing', 'speak English', 'write', 'count', 'cut', 'draw', 'color', 'boy', 'girl', 'listen to stories', 'clean up', 'food', 'colors', 'toys', 'friend', 'play', 'paint']::text[], ARRAY['What''s your (his/her) name? My (His/Her) name is (Dino).', 'Where is (Jimmy)? He''s / She''s not here.', 'What can Jimmy and Kelly do at school? They can sing.', 'Are you a boy or a girl? I''m a (boy/girl).', 'How old are you? I''m (five) years old.']::text[], 1
from richmond_units u where u.book_code = 'TG5A' and u.unit_number = 1
on conflict (unit_id, lesson_range) do update set
  lesson_start = excluded.lesson_start, lesson_end = excluded.lesson_end,
  learning_goals = excluded.learning_goals, vocabulary = excluded.vocabulary,
  language_models = excluded.language_models, sort_order = excluded.sort_order;

insert into richmond_lesson_groups (unit_id, lesson_range, lesson_start, lesson_end, learning_goals, vocabulary, language_models, sort_order)
select u.id, '5-8', 5, 8, ARRAY['To name the days of the school week', 'To trace the days of the school week', 'To identify special classes at school', 'To review numbers 1–20', 'To say when one has special classes and whether he/she likes them', 'To learn how to tell time on the hour', 'To identify special school activities and times']::text[], ARRAY['school days', 'PE', 'art', 'computer class', 'music', 'science', 'clock', 'time', 'numbers 1–12', 'days of the school week', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']::text[], ARRAY['What day is today? Today is Monday.', 'When do they have art? They have art on Tuesday.', 'Do we have music? Yes, we do. / No, we don''t.', 'Do you like science? Yes, I do. / No, I don''t.', 'What time is it? It''s six o''clock. Is it 8 o''clock? Yes, it is. / No, it isn''t. It''s 7 o''clock.']::text[], 2
from richmond_units u where u.book_code = 'TG5A' and u.unit_number = 1
on conflict (unit_id, lesson_range) do update set
  lesson_start = excluded.lesson_start, lesson_end = excluded.lesson_end,
  learning_goals = excluded.learning_goals, vocabulary = excluded.vocabulary,
  language_models = excluded.language_models, sort_order = excluded.sort_order;

insert into richmond_lesson_groups (unit_id, lesson_range, lesson_start, lesson_end, learning_goals, vocabulary, language_models, sort_order)
select u.id, '9-12', 9, 12, ARRAY['To name and trace the days of the school week', 'To identify and name weekend (recreational) activities', 'To trace days of the weekend', 'To say which activities one likes to do on the weekend', 'To identify and trace the parts of the day']::text[], ARRAY['weekday', 'weekend', 'Saturday', 'Sunday', 'go to the supermarket', 'visit my grandparents', 'go to the movies', 'stay home', 'play with my pet', 'play with my toys', 'play with my friends', 'watch TV', 'ride my bike', 'morning', 'afternoon', 'evening']::text[], ARRAY['We go to school (stay home) on (Monday).', 'What do you do on the weekend? I visit my grandparents on the weekend.', 'Do you like to play with your pet? Yes, I do. / No, I don''t.', 'When do you watch TV? In the morning, afternoon or evening? I watch TV in the (morning).', 'What''s Jimmy doing? He''s playing with his toys.', 'What does Dino do on Wednesdays? He plays video games with his friend.', 'Does Dino go to the movies on Tuesday? No, he doesn''t.']::text[], 3
from richmond_units u where u.book_code = 'TG5A' and u.unit_number = 1
on conflict (unit_id, lesson_range) do update set
  lesson_start = excluded.lesson_start, lesson_end = excluded.lesson_end,
  learning_goals = excluded.learning_goals, vocabulary = excluded.vocabulary,
  language_models = excluded.language_models, sort_order = excluded.sort_order;

insert into richmond_lesson_groups (unit_id, lesson_range, lesson_start, lesson_end, learning_goals, vocabulary, language_models, sort_order)
select u.id, '13-16', 13, 16, ARRAY['To identify more special classes', 'To listen attentively to a story', 'To predict what a story is about', 'To identify characters and feelings in a story', 'To sequence events in a story', 'To talk about activities one is good at and a new skill one would like to learn', 'To understand the importance of working hard to learn new things']::text[], ARRAY['karate', 'science', 'soccer', 'swimming', 'math', 'love', 'hate', 'good at', 'excited', 'scared', 'afraid', 'angry', 'bored', 'proud', 'sad', 'ride a bike', 'play tennis', 'do karate', 'play the recorder']::text[], ARRAY['She loves his/her class.', 'He/She is good at (soccer).', 'I''m (angry).', 'What class does Andy have on Wednesday? He has music class on Wednesday.', 'What time does he have his soccer class? He has his soccer class at 6 o''clock.', 'What''s he doing? He''s swimming.', 'Are you good at swimming? What are you good at? I''m good at (dancing).']::text[], 4
from richmond_units u where u.book_code = 'TG5A' and u.unit_number = 1
on conflict (unit_id, lesson_range) do update set
  lesson_start = excluded.lesson_start, lesson_end = excluded.lesson_end,
  learning_goals = excluded.learning_goals, vocabulary = excluded.vocabulary,
  language_models = excluded.language_models, sort_order = excluded.sort_order;

-- Unit 2: Look at My Family!
insert into richmond_lesson_groups (unit_id, lesson_range, lesson_start, lesson_end, learning_goals, vocabulary, language_models, sort_order)
select u.id, '1-4', 1, 4, ARRAY['To describe hair and eye color', 'To develop a concept of self', 'To describe hair type and eye color', 'To understand the concept that we are all special', 'To trace words that describe hair types']::text[], ARRAY['hair', 'eyes', 'brown', 'black', 'blond', 'blue', 'green', 'friend', 'boy', 'girl', 'long', 'short', 'curly', 'straight', 'red', 'small', 'big']::text[], ARRAY['What''s his/her name? Is he/she a boy or a girl? What color are his/her eyes? What color is his/her hair? I have brown hair and brown eyes.', 'My friend has black hair and green eyes. She''s a girl. She has curly, red hair. Is her hair long or short? It''s long. What color is her hair? It''s blond.', 'Does this (boy) have (curly) hair? Yes, (he) does. / No, (he) doesn''t. He has straight, blond hair and light blue eyes.']::text[], 1
from richmond_units u where u.book_code = 'TG5A' and u.unit_number = 2
on conflict (unit_id, lesson_range) do update set
  lesson_start = excluded.lesson_start, lesson_end = excluded.lesson_end,
  learning_goals = excluded.learning_goals, vocabulary = excluded.vocabulary,
  language_models = excluded.language_models, sort_order = excluded.sort_order;

insert into richmond_lesson_groups (unit_id, lesson_range, lesson_start, lesson_end, learning_goals, vocabulary, language_models, sort_order)
select u.id, '5-8', 5, 8, ARRAY['To identify family members', 'To describe family member''s physical traits', 'To compare one''s physical traits to those of a family member', 'To trace words that describe physical traits', 'To listen to a chant and follow again', 'To develop phonemic awareness']::text[], ARRAY['aunt', 'uncle', 'cousin', 'mother', 'father', 'brother', 'sister', 'grandpa', 'grandma', 'hair color', 'eye color', 'glasses', 'tall', 'short', 'fat', 'thin', 'young', 'old', 'family members', 'older', 'younger', 'taller', 'shorter', 'fatter', 'thinner']::text[], ARRAY['This is my uncle. He has black hair and brown eyes. Tell me about Jimmy''s aunt. What''s she like? She has blond hair and blue eyes.', 'Does Jimmy''s father have brown eyes? Yes, he does. / No, he doesn''t. Who''s she? She''s my aunt. What''s she like? She has blond hair and blue eyes. Who does she look like? She looks like Jimmy''s uncle. Who do you look like? I look like my (mom). She has brown hair. I have brown hair, too.']::text[], 2
from richmond_units u where u.book_code = 'TG5A' and u.unit_number = 2
on conflict (unit_id, lesson_range) do update set
  lesson_start = excluded.lesson_start, lesson_end = excluded.lesson_end,
  learning_goals = excluded.learning_goals, vocabulary = excluded.vocabulary,
  language_models = excluded.language_models, sort_order = excluded.sort_order;

insert into richmond_lesson_groups (unit_id, lesson_range, lesson_start, lesson_end, learning_goals, vocabulary, language_models, sort_order)
select u.id, '9-12', 9, 12, ARRAY['To understand that living things grow', 'To sort living and nonliving things', 'To sequence people by age', 'To trace words that describe people''s age', 'To compare people by height and age', 'To trace words that describe height and age', 'To learn to measure objects by centimeters']::text[], ARRAY['girl', 'woman', 'sprout', 'plant', 'puppy', 'dog', 'book', 'baby', 'kitten', 'robot', 'living things', 'grow', 'baby', 'boy', 'man', 'old man', 'older', 'younger', 'taller', 'shorter', 'growing', 'tall', 'taller', 'tallest', 'short', 'shorter', 'shortest', 'young', 'younger', 'youngest', 'old', 'older', 'oldest']::text[], ARRAY['What''s this? It''s a puppy. Do puppies grow? Yes. They grow up to be dogs. They are living things. Living things grow. Does a book grow? No, it doesn''t. It''s not a living thing.', 'The baby is very young. He is getting older. Who is older (younger, taller), the man or the baby? The man. Who''s taller, the mother or the sister? The mother is taller than the sister. Who''s the tallest? The father is the tallest.']::text[], 3
from richmond_units u where u.book_code = 'TG5A' and u.unit_number = 2
on conflict (unit_id, lesson_range) do update set
  lesson_start = excluded.lesson_start, lesson_end = excluded.lesson_end,
  learning_goals = excluded.learning_goals, vocabulary = excluded.vocabulary,
  language_models = excluded.language_models, sort_order = excluded.sort_order;

insert into richmond_lesson_groups (unit_id, lesson_range, lesson_start, lesson_end, learning_goals, vocabulary, language_models, sort_order)
select u.id, '13-16', 13, 16, ARRAY['To make predictions about what will happen in a story', 'To listen attentively and to follow a story', 'To make size comparisons', 'To trace words that describe size', 'To retell a story', 'To sequence events in a story', 'To trace sequence words', 'To talk about the importance of helping our siblings and family members']::text[], ARRAY['little', 'medium', 'big', 'goats', 'horses', 'oldest', 'fattest', 'thinnest', 'biggest', 'smallest', 'billy goats', 'bridge', 'river', 'troll', 'grass', 'first', 'then', 'next', 'finally', 'help my sibling get dressed', 'go to the park with my sibling', 'keep my sibling safe', 'play with my sibling', 'feed my sibling']::text[], ARRAY['What color is the little goat? White. Who''s bigger (fatter, thinner, older, younger) the (medium) goat or the (little) goat? Who''s this? Little Billy Goat. Who''s the oldest (youngest, fattest, thinnest)?', 'First, ... What happened? Then, ... What happened next? Next, ... What happened after that? Finally, ... What''s Dino (Dino''s sister) doing? Is he (she) helping his (her) sibling? Yes! He''s (She''s) helping his (her) baby brother get dressed. Dino (Dino''s sister) is helping his (her) sibling.']::text[], 4
from richmond_units u where u.book_code = 'TG5A' and u.unit_number = 2
on conflict (unit_id, lesson_range) do update set
  lesson_start = excluded.lesson_start, lesson_end = excluded.lesson_end,
  learning_goals = excluded.learning_goals, vocabulary = excluded.vocabulary,
  language_models = excluded.language_models, sort_order = excluded.sort_order;

-- Unit 3: Amazing Animals
insert into richmond_lesson_groups (unit_id, lesson_range, lesson_start, lesson_end, learning_goals, vocabulary, language_models, sort_order)
select u.id, '1-4', 1, 4, ARRAY['To identify and describe wild animals: singular and plural', 'To describe ongoing actions', 'To trace actions', 'To correct negative sentences', 'To count sets of animals', 'To add two sets of animals together']::text[], ARRAY['safari', 'elephant', 'zebra', 'lion', 'giraffe', 'hippo', 'crocodile', 'rhino', 'bird', 'monkey', 'tiger', 'gorilla', 'snake', 'drinking', 'climbing', 'walking', 'eating', 'flying', 'swimming', 'sleeping']::text[], ARRAY['What''s this? It''s an elephant. What are these? They are hippos. (This/That) is an elephant. (These/Those) are elephants.', 'What''s this? What''s it doing? It''s climbing. The little brown monkey is climbing.', 'Is it eating? Yes, it is. / No, it isn''t. Is the monkey climbing? Yes, it is. / No, it isn''t.', 'The bird isn''t eating. Are (the/those) rhinos swimming? Yes, they are. / No, they aren''t. How many lions are there? There are two lions. How many animals altogether? Two plus three equals five.']::text[], 1
from richmond_units u where u.book_code = 'TG5A' and u.unit_number = 3
on conflict (unit_id, lesson_range) do update set
  lesson_start = excluded.lesson_start, lesson_end = excluded.lesson_end,
  learning_goals = excluded.learning_goals, vocabulary = excluded.vocabulary,
  language_models = excluded.language_models, sort_order = excluded.sort_order;

insert into richmond_lesson_groups (unit_id, lesson_range, lesson_start, lesson_end, learning_goals, vocabulary, language_models, sort_order)
select u.id, '5-8', 5, 8, ARRAY['To identify wild animals and say how they move', 'To identify and trace actions', 'To follow directions', 'To describe the locations of animals', 'To identify and trace prepositions']::text[], ARRAY['jungle', 'running', 'swinging', 'hiding', 'crawling', 'standing', 'tiger', 'gorilla', 'snake', 'crocodile', 'in front of', 'behind', 'next to', 'on', 'between', 'plants', 'tree', 'rock']::text[], ARRAY['What are these? They are tigers. What are they doing? They''re running. What''s this? It''s a monkey. What''s it doing? It''s swinging.', 'Where''s the gorilla? It''s next to the tree. Where are the tigers? They''re behind the rock. The green crocodile is in front of the plants. Where''s the rhino? It''s behind the tree. Which animal is next to the rock? The snake is next to the rock.']::text[], 2
from richmond_units u where u.book_code = 'TG5A' and u.unit_number = 3
on conflict (unit_id, lesson_range) do update set
  lesson_start = excluded.lesson_start, lesson_end = excluded.lesson_end,
  learning_goals = excluded.learning_goals, vocabulary = excluded.vocabulary,
  language_models = excluded.language_models, sort_order = excluded.sort_order;

insert into richmond_lesson_groups (unit_id, lesson_range, lesson_start, lesson_end, learning_goals, vocabulary, language_models, sort_order)
select u.id, '9-12', 9, 12, ARRAY['To describe, compare and trace animal characteristics', 'To put animal types and characteristics into categories', 'To recognize characteristics of animals (in written form)', 'To describe, compare and trace animal body parts', 'To develop phonemic awareness', 'To identify zoo animals and body parts']::text[], ARRAY['big', 'small', 'spots', 'stripes', 'tiger', 'zebra', 'snake', 'giraffe', 'elephant', 'hippo', 'mouse', 'bird', 'long', 'short', 'big', 'small', 'ears', 'tails', 'legs', 'crocodile', 'panda', 'claws', 'tail', 'strong arms', 'horn', 'paws', 'teeth', 'zoo']::text[], ARRAY['This is a tiger. It has stripes. The tiger and zebra have stripes. The elephant has big ears. Does the giraffe have big ears? Yes, it does. / No, it doesn''t.', 'This is a lion. It has sharp claws. I''m thinking of an animal. Is it a snake? Yes, it is. / No, it isn''t. A lion and a tiger have sharp teeth. Do crocodiles have strong arms? Yes, they do. / No, they don''t. What do they have? They have sharp teeth. Which animal has a pointy horn? The rhino has a pointy horn.']::text[], 3
from richmond_units u where u.book_code = 'TG5A' and u.unit_number = 3
on conflict (unit_id, lesson_range) do update set
  lesson_start = excluded.lesson_start, lesson_end = excluded.lesson_end,
  learning_goals = excluded.learning_goals, vocabulary = excluded.vocabulary,
  language_models = excluded.language_models, sort_order = excluded.sort_order;

insert into richmond_lesson_groups (unit_id, lesson_range, lesson_start, lesson_end, learning_goals, vocabulary, language_models, sort_order)
select u.id, '13-16', 13, 16, ARRAY['To identify characters in a story', 'To make predictions about what a story is about', 'To describe how characters are feeling', 'To identify and trace the feeling words', 'To compare physical traits of story characters', 'To retell a story', 'To sequence a story', 'To recognize, count and sequence numbers to 20', 'To talk about the importance of being kind to others']::text[], ARRAY['happy', 'sad', 'scared', 'angry', 'strong', 'proud', 'big', 'small', 'lion', 'mouse', 'friend', 'hunter', 'trapped', 'net', 'chew', 'escape', 'kind', 'numbers 1–20', 'be kind', 'share my lunch', 'share my crayons', 'help a friend', 'share my ball', 'share my blocks', 'hurt someone''s feelings']::text[], ARRAY['How does the mouse feel? The mouse feels happy. The mouse is running on the lion. Does the lion have a long (short) tail? Yes, it does. (No, it doesn''t.) The lion has (doesn''t have) a long tail. Is the lion happy or angry? The lion is happy.', 'What number is this? It''s 10. What comes after 10? Eleven. How does the lion feel? The lion feels sad. What can the mouse do? The mouse can help the lion. Is the mouse kind? Yes, the mouse is kind. What is the yellow dinosaur doing? Is he being kind? Is he sharing his lunch? Yes, he is.']::text[], 4
from richmond_units u where u.book_code = 'TG5A' and u.unit_number = 3
on conflict (unit_id, lesson_range) do update set
  lesson_start = excluded.lesson_start, lesson_end = excluded.lesson_end,
  learning_goals = excluded.learning_goals, vocabulary = excluded.vocabulary,
  language_models = excluded.language_models, sort_order = excluded.sort_order;

-- Unit 4: I'm Healthy and Safe
insert into richmond_lesson_groups (unit_id, lesson_range, lesson_start, lesson_end, learning_goals, vocabulary, language_models, sort_order)
select u.id, '1-4', 1, 4, ARRAY['To identify, name and trace body parts', 'To distinguish right from left and trace the words left and right', 'To understand the importance of exercising to stay healthy', 'To review and count numbers 1 to 20', 'To add and subtract using fingers', 'To understand the meaning of +, - and = symbols']::text[], ARRAY['neck', 'arm', 'leg', 'hand', 'foot', 'head', 'shoulder', 'elbow', 'knee', 'ankle', 'right', 'left', 'numbers to 20', 'actions (hop, jump, touch, lift, shake, wave, wiggle, clap)', 'adding', 'subtracting', 'counting', 'fingers']::text[], ARRAY['What''s this? Neck. Touch your neck. How many elbows do you have? Two. I have two elbows. This is my right hand. Hop on your right foot. Wave your left hand. What''s this? This is Kelly''s left hand. Jimmy can hop eight times. Can you hop? Yes, I can. How many times? I can hop (five) times.', 'Addition: What number is this? Three. Show me three fingers. Three plus two equals five. Subtraction: Show me five fingers. Take away three. How many are left? Two.']::text[], 1
from richmond_units u where u.book_code = 'TG5A' and u.unit_number = 4
on conflict (unit_id, lesson_range) do update set
  lesson_start = excluded.lesson_start, lesson_end = excluded.lesson_end,
  learning_goals = excluded.learning_goals, vocabulary = excluded.vocabulary,
  language_models = excluded.language_models, sort_order = excluded.sort_order;

insert into richmond_lesson_groups (unit_id, lesson_range, lesson_start, lesson_end, learning_goals, vocabulary, language_models, sort_order)
select u.id, '5-8', 5, 8, ARRAY['To understand the importance of protecting one''s skin from the sun', 'To understand how to dress for different weather conditions', 'To describe what someone is wearing', 'To identify and differentiate between healthy and unhealthy habits', 'To understand the importance of developing healthy habits']::text[], ARRAY['the weather', 'sunscreen', 'clothing', 'eat healthy food', 'brush my teeth/hair', 'exercise', 'wash my hands', 'blow my nose/use a tissue', 'drink lots of water', 'take a shower', 'go to bed on time', 'stay up late', 'cover your sneeze', 'play', 'get rest', 'do my best']::text[], ARRAY['How''s the weather? It''s hot and sunny. What''s the girl wearing? She''s wearing a hat, sunglasses and sunscreen. What do you do to stay healthy? I (eat a healthy breakfast) to stay healthy.', 'Do you brush your teeth three times a day? Yes, I do. / No, I don''t. Eating an apple is healthy. Eating candy isn''t healthy.']::text[], 2
from richmond_units u where u.book_code = 'TG5A' and u.unit_number = 4
on conflict (unit_id, lesson_range) do update set
  lesson_start = excluded.lesson_start, lesson_end = excluded.lesson_end,
  learning_goals = excluded.learning_goals, vocabulary = excluded.vocabulary,
  language_models = excluded.language_models, sort_order = excluded.sort_order;

insert into richmond_lesson_groups (unit_id, lesson_range, lesson_start, lesson_end, learning_goals, vocabulary, language_models, sort_order)
select u.id, '9-12', 9, 12, ARRAY['To talk about how one feels', 'To recommend solutions', 'To identify and trace feelings words', 'To talk about ailments and remedies', 'To recommend solutions for getting better after being sick']::text[], ARRAY['tired', 'sick', 'hungry', 'thirsty', 'fan your face', 'put on your jacket', 'call the doctor', 'eat a cracker', 'drink some water', 'cough', 'sore throat', 'stomachache', 'fever', 'cold', 'cover your mouth', 'use a tissue', 'rest in bed']::text[], ARRAY['How do you feel? I''m tired. What does he need? He needs to drink water. What''s wrong with her? She has (doesn''t have) a headache.', 'I''m sick. I feel bad. I have a fever. What can I do to get better? I can tell my mom. I take medicine (drink water, rest in bed). What''s wrong? I have a cough. Have a drink of water.']::text[], 3
from richmond_units u where u.book_code = 'TG5A' and u.unit_number = 4
on conflict (unit_id, lesson_range) do update set
  lesson_start = excluded.lesson_start, lesson_end = excluded.lesson_end,
  learning_goals = excluded.learning_goals, vocabulary = excluded.vocabulary,
  language_models = excluded.language_models, sort_order = excluded.sort_order;

insert into richmond_lesson_groups (unit_id, lesson_range, lesson_start, lesson_end, learning_goals, vocabulary, language_models, sort_order)
select u.id, '13-16', 13, 16, ARRAY['To differentiate between safe and unsafe practices on the playground', 'To retell a story', 'To describe common, minor injuries', 'To talk about the importance of playing safely with friends on the playground']::text[], ARRAY['safe', 'dangerous', 'be careful', 'slide', 'skateboard', 'bike', 'helmet', 'swing', 'climbing frame', 'hurt', 'scraped', 'broke', 'cut', 'bumped', 'see-saw', 'take turns', 'run after a ball', 'street', 'ride my bike', 'jump']::text[], ARRAY['What''s this boy doing? He''s riding his bike. Wear your helmet when you ride your bike. She''s swinging on the swing. Is that safe? Yes. She knows how to swing safely.', 'What''s he doing? He''s jumping off the swing. Don''t jump off the swing. I scraped/hurt my knee. The boy scraped his knee. They are playing on the slide. Are they taking turns? Yes. They are taking turns.']::text[], 4
from richmond_units u where u.book_code = 'TG5A' and u.unit_number = 4
on conflict (unit_id, lesson_range) do update set
  lesson_start = excluded.lesson_start, lesson_end = excluded.lesson_end,
  learning_goals = excluded.learning_goals, vocabulary = excluded.vocabulary,
  language_models = excluded.language_models, sort_order = excluded.sort_order;

-- Unit 5: My Community
insert into richmond_lesson_groups (unit_id, lesson_range, lesson_start, lesson_end, learning_goals, vocabulary, language_models, sort_order)
select u.id, '1-4', 1, 4, ARRAY['To identify and name places in a town', 'To use polite responses: thank you, you''re welcome, sorry', 'To count by 10''s to 100', 'To say one''s address', 'To identify and name stores', 'To associate products with stores']::text[], ARRAY['school', 'fire station', 'police station', 'dentist', 'hospital', 'post office', 'restaurant', 'clothing/toy/pet store', 'supermarket', 'park', 'house', '10', '20', '30', '40', '50', '60', '70', '80', '90', '100']::text[], ARRAY['There''s a (clothing store) in my town. Is there a restaurant in town? Yes, there is. Where is it? Here it is. Thank you. You''re welcome.', 'Is there a (pet store) in town? Sorry. No, there isn''t. Do you live in a house or an apartment? I live in a house. What''s the address on the (fire station)? (50). What''s your address? My address is (3-0-5) (Yaqui) Street. This is a pet store. I''m looking for some eggs. Where can I buy eggs? You can buy eggs at the supermarket.']::text[], 1
from richmond_units u where u.book_code = 'TG5A' and u.unit_number = 5
on conflict (unit_id, lesson_range) do update set
  lesson_start = excluded.lesson_start, lesson_end = excluded.lesson_end,
  learning_goals = excluded.learning_goals, vocabulary = excluded.vocabulary,
  language_models = excluded.language_models, sort_order = excluded.sort_order;

insert into richmond_lesson_groups (unit_id, lesson_range, lesson_start, lesson_end, learning_goals, vocabulary, language_models, sort_order)
select u.id, '5-8', 5, 8, ARRAY['To identify and name healthcare workers', 'To identify and trace the words for dentist, doctor, nurse', 'To identify tools and to associate them with workers', 'To learn about taking care of one''s teeth', 'To understand the importance of going to the doctor when one is sick']::text[], ARRAY['doctor', 'dentist', 'nurse', 'hospital', 'dental clinic', 'community helpers', 'doctor''s tools', 'dentist''s tools', 'nurse''s tools', 'sick', 'call the doctor', 'doctor''s bag', 'hat', 'shake his head', 'chill', 'pill']::text[], ARRAY['Who''s she? She''s a doctor. Where do doctors work? Doctors work in the hospital. What do doctors do? Doctors keep us healthy.', 'Who''s he? He''s a dentist. What''s he doing? He''s checking the girl''s teeth. What''s this? This is a (mirror). Who uses this? A dentist. I brush my teeth three times a day. I floss my teeth. Brush your teeth after you eat candy.']::text[], 2
from richmond_units u where u.book_code = 'TG5A' and u.unit_number = 5
on conflict (unit_id, lesson_range) do update set
  lesson_start = excluded.lesson_start, lesson_end = excluded.lesson_end,
  learning_goals = excluded.learning_goals, vocabulary = excluded.vocabulary,
  language_models = excluded.language_models, sort_order = excluded.sort_order;

insert into richmond_lesson_groups (unit_id, lesson_range, lesson_start, lesson_end, learning_goals, vocabulary, language_models, sort_order)
select u.id, '9-12', 9, 12, ARRAY['To identify community helpers', 'To say where people work and what they do at work', 'To say what tools people use at work', 'To say what professions family members have', 'To say what one wants to be when he or she grows up']::text[], ARRAY['uniform', 'police officer', 'vet', 'salesperson', 'firefighter', 'server', 'mail carrier', 'police station', 'pet store', 'toystore', 'fire station', 'restaurant', 'post office', 'teacher', 'badge', 'hose', 'stethoscope', 'mail bag']::text[], ARRAY['Who''s she? She''s a police officer. Where does she work? She works at the police station. What does a police officer do? A police officer keeps us safe.', 'Who''s he? He''s a firefighter. What does a firefighter do? A firefighter puts out fires. What''s this? It''s a hose. Who''s she? She''s a vet. What does a vet do? A vet takes care of animals. What does your mom do? She''s a (server). What do you want to be when you grow up? I want to be an artist.']::text[], 3
from richmond_units u where u.book_code = 'TG5A' and u.unit_number = 5
on conflict (unit_id, lesson_range) do update set
  lesson_start = excluded.lesson_start, lesson_end = excluded.lesson_end,
  learning_goals = excluded.learning_goals, vocabulary = excluded.vocabulary,
  language_models = excluded.language_models, sort_order = excluded.sort_order;

insert into richmond_lesson_groups (unit_id, lesson_range, lesson_start, lesson_end, learning_goals, vocabulary, language_models, sort_order)
select u.id, '13-16', 13, 16, ARRAY['To talk about traffic and safety rules', 'To understand rules to stay safe when crossing the street', 'To understand and trace the words Walk and Don''t walk', 'To consider how the characters in the story feel', 'To talk about the importance of staying safe and following safety rules']::text[], ARRAY['safe', 'dangerous', 'careful', 'sidewalk', 'street', 'car', 'seat belt', 'traffic', 'crossing light', 'helmet', 'restaurant', 'taxi', 'wear (unbuckle) your seat belt', 'crosswalk', 'stop', 'go', 'bike', 'skateboard', 'knee and elbow pads', 'taxi', 'red', 'yellow and green lights', 'sidewalk']::text[], ARRAY['Mommy Gorilla is helping Little Gorilla get out of the car. They are waiting to cross the street. What''s Little Gorilla doing? He''s unbuckling his seat belt. Is that safe or dangerous? It''s safe.', 'The sign says "Don''t walk." Stay on the sidewalk. The light is red. Look both ways. Now you can cross the street.']::text[], 4
from richmond_units u where u.book_code = 'TG5A' and u.unit_number = 5
on conflict (unit_id, lesson_range) do update set
  lesson_start = excluded.lesson_start, lesson_end = excluded.lesson_end,
  learning_goals = excluded.learning_goals, vocabulary = excluded.vocabulary,
  language_models = excluded.language_models, sort_order = excluded.sort_order;

-- Unit 6: Saving the Planet
insert into richmond_lesson_groups (unit_id, lesson_range, lesson_start, lesson_end, learning_goals, vocabulary, language_models, sort_order)
select u.id, '1-4', 1, 4, ARRAY['To identify elements of nature', 'To differentiate between land and water', 'To understand that we share the planet and that we need to take care of it', 'To identify animals and classify them by where they live: air, land, water', 'To identify and sort natural and man-made objects']::text[], ARRAY['Planet Earth', 'water', 'sea', 'ocean', 'land', 'country', 'forest', 'mountain', 'river', 'fish', 'air', 'lake', 'trees', 'bird', 'deer', 'fox', 'squirrel', 'frog', 'duck', 'sky', 'natural', 'man-made', 'leaf', 'soda can', 'flower', 'butterfly', 'building', 'ball', 'clouds', 'grass']::text[], ARRAY['The Earth is our home. This is the land (water). We live on the land. Animals live on the land, in the sky, and in the water. We share the Earth with the animals. This is natural. It''s part of the natural world.', 'This is man-made. A person made it.']::text[], 1
from richmond_units u where u.book_code = 'TG5A' and u.unit_number = 6
on conflict (unit_id, lesson_range) do update set
  lesson_start = excluded.lesson_start, lesson_end = excluded.lesson_end,
  learning_goals = excluded.learning_goals, vocabulary = excluded.vocabulary,
  language_models = excluded.language_models, sort_order = excluded.sort_order;

insert into richmond_lesson_groups (unit_id, lesson_range, lesson_start, lesson_end, learning_goals, vocabulary, language_models, sort_order)
select u.id, '5-8', 5, 8, ARRAY['To understand that litter is a problem', 'To identify and describe the location of trash items', 'To understand that we need clean air/water and what air/water pollution is', 'To introduce how we can take care of the Earth by reducing, reusing and recycling']::text[], ARRAY['environment', 'clean', 'polluted', 'air/water pollution', 'factory litter', 'glass/plastic bottle', 'plastic rings', 'in', 'on', 'under', 'next to', 'between', 'sea', 'lake', 'pond', 'river', 'plastic bags', 'juice boxes', 'reduce', 'reuse', 'recycle']::text[], ARRAY['We can pick up the litter. It''s in the sandbox. It''s on the bench. We need clean air to breathe. There is smoke coming from the factories, cars and buses.', 'Is the pond polluted? No, it isn''t. It''s clean. What''s polluting the water? A plastic bag. What can we do to help the Earth? We can put litter in the trash. We can use things again.']::text[], 2
from richmond_units u where u.book_code = 'TG5A' and u.unit_number = 6
on conflict (unit_id, lesson_range) do update set
  lesson_start = excluded.lesson_start, lesson_end = excluded.lesson_end,
  learning_goals = excluded.learning_goals, vocabulary = excluded.vocabulary,
  language_models = excluded.language_models, sort_order = excluded.sort_order;

insert into richmond_lesson_groups (unit_id, lesson_range, lesson_start, lesson_end, learning_goals, vocabulary, language_models, sort_order)
select u.id, '9-12', 9, 12, ARRAY['To understand that water and electricity are natural resources and we need them', 'To understand the concepts of saving and wasting water and electricity', 'To understand the importance of recycling', 'To sort trash by type', 'To count to 100 by tens']::text[], ARRAY['water', 'electricity', 'use lights', 'hose', 'watering can', 'trash', 'can', 'plant a tree', 'save', 'waste', 'recycle', 'plastic', 'metal', 'paper', 'recycling box', 'numbers to 100 (by tens)', 'reuse', 'plastic container']::text[], ARRAY['He''s watching TV. He''s using electricity/water. Don''t run the water when you brush your teeth. It''s a newspaper. Which box does the newspaper go into? Paper.', 'How many dots are there? 10. How many sets of 10 are there? Three. How many is that? 30.']::text[], 3
from richmond_units u where u.book_code = 'TG5A' and u.unit_number = 6
on conflict (unit_id, lesson_range) do update set
  lesson_start = excluded.lesson_start, lesson_end = excluded.lesson_end,
  learning_goals = excluded.learning_goals, vocabulary = excluded.vocabulary,
  language_models = excluded.language_models, sort_order = excluded.sort_order;

insert into richmond_lesson_groups (unit_id, lesson_range, lesson_start, lesson_end, learning_goals, vocabulary, language_models, sort_order)
select u.id, '13-16', 13, 16, ARRAY['To identify sea animals', 'To listen to, follow and sequence a story', 'To understand the importance of not polluting the ocean/sea', 'To recognize the importance of looking for solutions', 'To review numbers (multiples of 10 to 100) and colors', 'To talk about the importance of taking care of the Earth and sea animals']::text[], ARRAY['plastic bag', 'float', 'dolphins', 'boat', 'trash', 'soda', 'cooler', 'sea', 'sea turtles', 'pollution', 'clean', 'safe', 'river', 'whale', 'shark', 'jellyfish', 'starfish', 'octopus', 'coral', 'recycle', 'sort', 'turn off the water', 'plastic bottle', 'litter', 'plant a tree']::text[], ARRAY['What happens next? The dolphins are swimming next to the plastic bag. The trash falls in the river. I think the blue whales are going to eat the trash.', 'What''s this? It''s a jellyfish. What color is the jellyfish? Put your finger on the dolphin with number 100. What are the dinosaurs doing? Are they sorting their trash? Yes, they are. / No, they aren''t.']::text[], 4
from richmond_units u where u.book_code = 'TG5A' and u.unit_number = 6
on conflict (unit_id, lesson_range) do update set
  lesson_start = excluded.lesson_start, lesson_end = excluded.lesson_end,
  learning_goals = excluded.learning_goals, vocabulary = excluded.vocabulary,
  language_models = excluded.language_models, sort_order = excluded.sort_order;

-- Unit 7: Going Places
insert into richmond_lesson_groups (unit_id, lesson_range, lesson_start, lesson_end, learning_goals, vocabulary, language_models, sort_order)
select u.id, '1-4', 1, 4, ARRAY['To identify weather conditions', 'To describe what people are wearing', 'To identify and name activities related to each season', 'To trace the names of the seasons', 'To express where one wants to go and do', 'To name seasons and months of the year']::text[], ARRAY['weather', 'clothing', 'colors', 'seasons (winter, spring, summer, fall)', 'play in the snow/sand/leaves', 'mountains', 'theme park', 'beach', 'campsite', 'swimming', 'hiking', 'skiing']::text[], ARRAY['What''s the weather like? It''s hot and sunny. What''s (Jimmy) wearing? He''s wearing a T-shirt, shorts, socks and tennis shoes. What season is this? It''s spring.', 'Where does Dino want to go? He wants to go (to the beach). What does he like to do? He likes to ride on the roller coaster. What months are in the winter? December, January and February.']::text[], 1
from richmond_units u where u.book_code = 'TG5A' and u.unit_number = 7
on conflict (unit_id, lesson_range) do update set
  lesson_start = excluded.lesson_start, lesson_end = excluded.lesson_end,
  learning_goals = excluded.learning_goals, vocabulary = excluded.vocabulary,
  language_models = excluded.language_models, sort_order = excluded.sort_order;

insert into richmond_lesson_groups (unit_id, lesson_range, lesson_start, lesson_end, learning_goals, vocabulary, language_models, sort_order)
select u.id, '5-8', 5, 8, ARRAY['To identify forms of transportation and transportation locations', 'To talk about vacation plans and the seasons', 'To tell time on the half hour', 'To review and recognize numbers to 20', 'To talk about buying tickets, departure times and choosing a seat', 'To count to 100 by tens']::text[], ARRAY['plane', 'train', 'bus', 'taxi', 'car', 'airport', 'train station', 'bus station', 'taxi stand', 'bus ticket', 'time', 'seat', 'numbers to 20', 'flight', 'time', 'numbers 10 to 100', 'airport', 'bus station']::text[], ARRAY['Where''s Dino? He''s at the airport. Where''s he going? He''s going to the beach. How''s he getting there? By plane. When''s Dino going to the beach? In the summer.', 'What time is it? It''s 2:30. What time does the bus leave? At 10:30. What''s your seat number? (Seven). What''s the flight number? Number 40.']::text[], 2
from richmond_units u where u.book_code = 'TG5A' and u.unit_number = 7
on conflict (unit_id, lesson_range) do update set
  lesson_start = excluded.lesson_start, lesson_end = excluded.lesson_end,
  learning_goals = excluded.learning_goals, vocabulary = excluded.vocabulary,
  language_models = excluded.language_models, sort_order = excluded.sort_order;

insert into richmond_lesson_groups (unit_id, lesson_range, lesson_start, lesson_end, learning_goals, vocabulary, language_models, sort_order)
select u.id, '9-12', 9, 12, ARRAY['To identify vacation destinations, forms of transportation and lodging', 'To describe vacation-related activities', 'To identify and trace the words for vacation locations', 'To plan a vacation and talk about packing for a trip', 'To identify clothing needed for different kinds of weather']::text[], ARRAY['beach', 'mountains', 'plane', 'taxi', 'hotel', 'house', 'tent', 'cabin', 'vacation activities', 'weather-related clothing and items']::text[], ARRAY['Where are you going to go on vacation? I''m going to go to the beach. What are you going to do at the beach? I''m going to swim.', 'How do you want to get there? I want to go by plane. Where do you want to stay? I want to stay in a tent. How''s the weather? It''s cold. What''s she taking? She''s taking a coat and boots.']::text[], 3
from richmond_units u where u.book_code = 'TG5A' and u.unit_number = 7
on conflict (unit_id, lesson_range) do update set
  lesson_start = excluded.lesson_start, lesson_end = excluded.lesson_end,
  learning_goals = excluded.learning_goals, vocabulary = excluded.vocabulary,
  language_models = excluded.language_models, sort_order = excluded.sort_order;

insert into richmond_lesson_groups (unit_id, lesson_range, lesson_start, lesson_end, learning_goals, vocabulary, language_models, sort_order)
select u.id, '13-16', 13, 16, ARRAY['To describe actions in the past', 'To listen and follow a story', 'To discuss the importance of helping each other', 'To describe how they and other characters felt about a situation', 'To understand the importance of working together as a family']::text[], ARRAY['put up a tent', 'went hiking', 'built a campfire', 'slept in a tent', 'rode (drove)', 'fell down', 'helped', 'dropped', 'pulled back into boat']::text[], ARRAY['They went camping. What did they do? They (put up a tent). They went camping. What happened? Little Brother fell down. Who helped him? Dad helped him.', 'What are the dinosaurs doing? The dinosaurs are working together to put up a tent!']::text[], 4
from richmond_units u where u.book_code = 'TG5A' and u.unit_number = 7
on conflict (unit_id, lesson_range) do update set
  lesson_start = excluded.lesson_start, lesson_end = excluded.lesson_end,
  learning_goals = excluded.learning_goals, vocabulary = excluded.vocabulary,
  language_models = excluded.language_models, sort_order = excluded.sort_order;

-- Unit 8: Present, Past and Future
insert into richmond_lesson_groups (unit_id, lesson_range, lesson_start, lesson_end, learning_goals, vocabulary, language_models, sort_order)
select u.id, '1-4', 1, 4, ARRAY['To sort items babies and children use', 'To say which activities a baby can and cannot do', 'To identify the written words yes and no', 'To compare activities a child/baby can do independently', 'To understand that students are becoming more independent as they grow']::text[], ARRAY['handprint', 'bed', 'crib', 'shoe', 'toy', 'rattle', 'changing', 'growing', 'cry', 'crawl', 'write your name', 'take a bath by yourself', 'drink from a bottle', 'use scissors', 'tie your shoes', 'brush my hair', 'get dressed', 'brush my teeth', 'put on my socks', 'grow and change']::text[], ARRAY['This is a picture of me when I was a baby. That was a long time ago. It''s a rattle. A baby uses a rattle. Babies can''t write but children can. Babies can sit and sleep in their cribs.', 'Children can read books. What could Dino do when he was a baby? (He could) sleep in a crib.']::text[], 1
from richmond_units u where u.book_code = 'TG5A' and u.unit_number = 8
on conflict (unit_id, lesson_range) do update set
  lesson_start = excluded.lesson_start, lesson_end = excluded.lesson_end,
  learning_goals = excluded.learning_goals, vocabulary = excluded.vocabulary,
  language_models = excluded.language_models, sort_order = excluded.sort_order;

insert into richmond_lesson_groups (unit_id, lesson_range, lesson_start, lesson_end, learning_goals, vocabulary, language_models, sort_order)
select u.id, '5-8', 5, 8, ARRAY['To talk about new technology and modern devices', 'To talk about technology and devices used in the past', 'To compare and sort modern and old devices', 'To match the same types of devices from the present and the past']::text[], ARRAY['laptop', 'tablet', 'TV', 'video games', 'cell phone', 'video call', 'long ago', 'now', 'telephone', 'typewriter', 'record player', 'radio', 'new', 'past', 'present', 'game', 'old toy', 'old camera', 'old board game', 'remote toy', 'selfie', 'digital music']::text[], ARRAY['Kelly''s calling grandma on the computer. He''s playing a game on the tablet. This is Grandma when she was six. That was long ago. This was grandma''s TV. She didn''t have a computer but she had a typewriter.', 'These are things grandma used in the past. These are things we use in the present.']::text[], 2
from richmond_units u where u.book_code = 'TG5A' and u.unit_number = 8
on conflict (unit_id, lesson_range) do update set
  lesson_start = excluded.lesson_start, lesson_end = excluded.lesson_end,
  learning_goals = excluded.learning_goals, vocabulary = excluded.vocabulary,
  language_models = excluded.language_models, sort_order = excluded.sort_order;

insert into richmond_lesson_groups (unit_id, lesson_range, lesson_start, lesson_end, learning_goals, vocabulary, language_models, sort_order)
select u.id, '9-12', 9, 12, ARRAY['To say the days of the week in order', 'To understand the concept of yesterday, today and tomorrow', 'To understand a schedule of events', 'To understand that we change and grow', 'To talk about things a robot can do', 'To use imagination to create a robot']::text[], ARRAY['days of the week', 'music', 'PE', 'science', 'computer class', 'stay home', 'past', 'present', 'future', 'yesterday', 'today', 'tomorrow', 'baby', 'adult', 'grown-up', 'robot', 'play', 'fly', 'do homework', 'clean', 'talk', 'dance']::text[], ARRAY['Dino had music class yesterday. He has art class today. They have art class on Tuesday. This is me when I was a baby. This is me now.', 'This is what I think I''ll look like when I grow up. What can his robot do? It can talk. Can it do homework? Yes, it can. Can it swim? No, it can''t.']::text[], 3
from richmond_units u where u.book_code = 'TG5A' and u.unit_number = 8
on conflict (unit_id, lesson_range) do update set
  lesson_start = excluded.lesson_start, lesson_end = excluded.lesson_end,
  learning_goals = excluded.learning_goals, vocabulary = excluded.vocabulary,
  language_models = excluded.language_models, sort_order = excluded.sort_order;

insert into richmond_lesson_groups (unit_id, lesson_range, lesson_start, lesson_end, learning_goals, vocabulary, language_models, sort_order)
select u.id, '13-16', 13, 16, ARRAY['To answer questions about a story', 'To discuss children''s chores and routines', 'To make predictions and talk about life in the future', 'To understand that as we grow and change, we can do new things', 'To reflect on what has been learned at school this year and make plans for next year']::text[], ARRAY['crash', 'helmet', 'spaceship', 'buttons', 'robot', 'chores', 'clean your room', 'do your homework', 'brush your teeth', 'futuristic car/refrigerator', 'robot cleaner', 'robot dog', 'enjoy my work', 'try my best', 'share my ideas', 'work with others', 'this year', 'next year']::text[], ARRAY['Judy meets Peter''s parents on Planet X. He''s brushing his teeth. What chore does he have to do? He has to clean his room. It''s a futuristic car. What does it do? It flies in the sky.', 'What can you do now that you couldn''t do when you were a baby? I can (count to 20). How many of you enjoyed your work in this class? Raise your hands. Circle the third star if you really enjoyed your work in this class.']::text[], 4
from richmond_units u where u.book_code = 'TG5A' and u.unit_number = 8
on conflict (unit_id, lesson_range) do update set
  lesson_start = excluded.lesson_start, lesson_end = excluded.lesson_end,
  learning_goals = excluded.learning_goals, vocabulary = excluded.vocabulary,
  language_models = excluded.language_models, sort_order = excluded.sort_order;

